[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://www.googletagmanager.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co https://www.googleapis.com; frame-src 'self'; object-src 'none'; base-uri 'self';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Set cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set cache headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment variable configuration
[context.production.environment]
  VITE_APP_ENV = "production"
  VITE_ENABLE_OFFLINE_MODE = "true"
  VITE_ENABLE_PUSH_NOTIFICATIONS = "true"
  VITE_ENABLE_ANALYTICS = "true"
  VITE_ENABLE_PERFORMANCE_MONITORING = "true"
  VITE_ENABLE_ERROR_REPORTING = "true"
  VITE_CSP_MODE = "strict"

[context.deploy-preview.environment]
  VITE_APP_ENV = "preview"
  VITE_ENABLE_OFFLINE_MODE = "true"
  VITE_ENABLE_PUSH_NOTIFICATIONS = "false"
  VITE_ENABLE_ANALYTICS = "false"
  VITE_ENABLE_PERFORMANCE_MONITORING = "true"
  VITE_ENABLE_ERROR_REPORTING = "true"
  VITE_CSP_MODE = "moderate"

[context.branch-deploy.environment]
  VITE_APP_ENV = "development"
  VITE_ENABLE_OFFLINE_MODE = "true"
  VITE_ENABLE_PUSH_NOTIFICATIONS = "false"
  VITE_ENABLE_ANALYTICS = "false"
  VITE_ENABLE_PERFORMANCE_MONITORING = "false"
  VITE_ENABLE_ERROR_REPORTING = "true"
  VITE_CSP_MODE = "relaxed"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://echomind.netlify.app"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google",
      "bing"
    ]
